meta_product_name: "Reset"
meta_title: "Reset - Take care of your mental health by taking a mindful walk to a greenspace"
meta_description: "Relevant description"
meta_image: "logo_light.png" # should exist in `app/assets/images/`
